import type { Metadata } from "next";
import { Kodchasan } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/organisms/header/header";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const kodchasan = Kodchasan({
  weight: ["300", "500", "700"],
  style: "normal",
  subsets: ["latin"],
  fallback: ["Inter"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={kodchasan.className}>
          <Header />

          <main>{children}</main>

          <footer></footer>
        </body>
      </UserProvider>
    </html>
  );
}
