import type { Metadata } from "next";
import { Kodchasan } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/organisms/header/header";
import firebase from "firebase/compat/app";
import { firebaseConfig } from "./lib/firebase/config";

const kodchasan = Kodchasan({
  weight: ["300", "500", "700"],
  style: "normal",
  subsets: ["latin"],
  fallback: ["Inter"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kodchasan.className}>
        <Header />

        <main>{children}</main>

        <footer></footer>
      </body>
    </html>
  );
}
